### ISSUE TITLE
SSL HandShake failed

### ISSUE THREAD

**Issue by linuxipho** [ekylibre/zero-android#64]
SSL Handshake failed every time since restricting only to TLSv1.2 on server part configuration

```
javax.net.ssl.SSLHandshakeException:` Handshake failed
02-19 14:00:21.152 W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:444)
02-19 14:00:21.152 W/System.err:     at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:406)
02-19 14:00:21.152 W/System.err:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:219)
02-19 14:00:21.153 W/System.err:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:172)
02-19 14:00:21.153 W/System.err:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:130)
02-19 14:00:21.153 W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.executeOriginal(DefaultRequestDirector.java:1334)
02-19 14:00:21.153 W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:700)
02-19 14:00:21.153 W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
02-19 14:00:21.153 W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
02-19 14:00:21.153 W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
02-19 14:00:21.154 W/System.err:     at ekylibre.APICaller.Instance.getJSONArray(Instance.java:267)
02-19 14:00:21.154 W/System.err:     at ekylibre.APICaller.Instance.getJSONArray(Instance.java:238)
02-19 14:00:21.154 W/System.err:     at ekylibre.APICaller.Intervention.all(Intervention.java:56)
02-19 14:00:21.154 W/System.err:     at ekylibre.APICaller.SyncAdapter.pullIntervention(SyncAdapter.java:454)
02-19 14:00:21.154 W/System.err:     at ekylibre.APICaller.SyncAdapter.onPerformSync(SyncAdapter.java:138)
02-19 14:00:21.154 W/System.err:     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
02-19 14:00:21.155 W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0xdda74dc0: Failure in SSL library, usually a protocol error
02-19 14:00:21.155 W/System.err: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/s3_pkt.c:641 0xdda21360:0x00000001)
02-19 14:00:21.155 W/System.err: error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/s3_clnt.c:800 0xdbcb9a9f:0x00000000)
02-19 14:00:21.155 W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
02-19 14:00:21.155 W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:364)
02-19 14:00:21.155 W/System.err: 	... 15 more
```

**Comment by linuxipho** [comment]
Error still happening on login page
